/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.mypixel.processor;

import java.lang.*;

public class App {

    public static void main(String[] args) {
        Hello hello = new Hello();
        hello.sayHello();
    }
}
