/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_mypixel_processor_Hello */

#ifndef _Included_com_example_mypixel_processor_Hello
#define _Included_com_example_mypixel_processor_Hello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_mypixel_processor_Hello
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_mypixel_processor_Hello_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
