/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_mypixel_processor_OpenCv */

#ifndef _Included_com_example_mypixel_processor_OpenCv
#define _Included_com_example_mypixel_processor_OpenCv
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_mypixel_processor_OpenCv
 * Method:    hi
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_mypixel_processor_OpenCv_hi
  (JNIEnv *, jobject);

#ifdef __cplusplus
}

#endif
#endif
