services:
  engine:
    image: polinapolupan/pixel-engine:latest
    ports:
      - '8080:8080'
    environment:
      APP_NAME: pixel-engine
      STORAGE_DIRECTORY: /app/storage
      NODE_SERVICE_URL: http://node:8000
    volumes:
      - ./engine-storage:/app/storage

  node:
    image: polinapolupan/pixel-node:latest
    ports:
      - '8000:8000'
    environment:
      ENGINE_SERVICE_URL: http://engine:8080
    volumes:
      - ./node-storage:/app/storage

  frontend:
    image: polinapolupan/pixel-frontend:latest
    ports:
      - '5173:5173'
    environment:
      NODE_ENV: production