services:
  engine:
    image: polinapolupan/pixel-engine:latest
    ports:
      - '8080:8080'
    environment:
      APP_NAME: ${APP_NAME}
      DATA_DIR: ${DATA_DIR}
      DUMP_DIR: ${DUMP_DIR}
      NODE_SERVICE_URL: ${NODE_SERVICE_URL}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
    volumes:
      - ../${DATA_DIR}:/app/${DATA_DIR}

  node:
    image: polinapolupan/pixel-node:latest
    ports:
      - '8000:8000'
    environment:
      ENGINE_SERVICE_URL: ${ENGINE_SERVICE_URL}
      EXECUTION_GRAPH_DIR: ${EXECUTION_GRAPH_DIR}
    volumes:
      - ../${EXECUTION_GRAPH_DIR}:/app/${EXECUTION_GRAPH_DIR}

  frontend:
    image: polinapolupan/pixel-frontend:latest
    ports:
      - '5173:5173'
    environment:
      NODE_ENV: production