/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_mypixel_service_FilteringServiceNative */

#ifndef _Included_com_example_mypixel_service_FilteringServiceNative
#define _Included_com_example_mypixel_service_FilteringServiceNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_mypixel_service_FilteringServiceNative
 * Method:    gaussianBlur
 * Signature: (Ljava/lang/String;IIDD)V
 */
JNIEXPORT void JNICALL Java_com_example_mypixel_service_FilteringServiceNative_gaussianBlur
  (JNIEnv *, jobject, jstring, jint, jint, jdouble, jdouble);

/*
 * Class:     com_example_mypixel_service_FilteringServiceNative
 * Method:    medianBlur
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_example_mypixel_service_FilteringServiceNative_medianBlur
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_example_mypixel_service_FilteringServiceNative
 * Method:    blur
 * Signature: (Ljava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_com_example_mypixel_service_FilteringServiceNative_blur
  (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     com_example_mypixel_service_FilteringServiceNative
 * Method:    bilateralFilter
 * Signature: (Ljava/lang/String;IDD)V
 */
JNIEXPORT void JNICALL Java_com_example_mypixel_service_FilteringServiceNative_bilateralFilter
  (JNIEnv *, jobject, jstring, jint, jdouble, jdouble);

/*
 * Class:     com_example_mypixel_service_FilteringServiceNative
 * Method:    boxFilter
 * Signature: (Ljava/lang/String;III)V
 */
JNIEXPORT void JNICALL Java_com_example_mypixel_service_FilteringServiceNative_boxFilter
  (JNIEnv *, jobject, jstring, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
