/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_mypixel_service_FilteringService */

#ifndef _Included_com_example_mypixel_service_FilteringService
#define _Included_com_example_mypixel_service_FilteringService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_mypixel_service_FilteringService
 * Method:    gaussianBlurNative
 * Signature: (Ljava/lang/String;IIDD)V
 */
JNIEXPORT void JNICALL Java_com_example_mypixel_service_FilteringService_gaussianBlurNative
  (JNIEnv *, jobject, jstring, jint, jint, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
