name: Build and Push Engine Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'engine/**'
      - '.github/workflows/docker-engine.yml'

jobs:
  build-gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build with Gradle
        working-directory: ./engine
        run: ./gradlew build -x test --no-daemon

  build-and-push-engine:
    needs: build-gradle
    uses: ./.github/workflows/docker-build-push.yml
    with:
      service: engine
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
