name: Build and Push Engine Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'engine/**'
      - '.github/workflows/docker-engine.yml'

jobs:
  build-gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build with Gradle
        working-directory: ./engine
        run: ./gradlew build -x test --no-daemon
        
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: engine-artifacts
          path: engine/build/libs/

  build-and-push-engine:
    needs: build-gradle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: engine-artifacts
          path: engine/build/libs/
          
      - uses: docker/setup-buildx-action@v3
      
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - uses: docker/build-push-action@v5
        with:
          context: ./engine
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pixel-engine:latest
