name: Sdk PyPi publishing

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install build tools
        run: python -m pip install --upgrade build

      - name: Build package
        working-directory: sdk
        run: |
          rm -rf build dist *.egg-info
          python -m build

      - name: Inspect wheel METADATA
        working-directory: sdk
        run: |
          unzip -p dist/pixel_sdk-*.whl *.dist-info/METADATA || echo "No METADATA"

      - name: Publish with Twine
        run: |
          pip install twine
          twine upload --repository pypi sdk/dist/*.whl -u __token__ -p ${{ secrets.PYPI_API_TOKEN }}
