name: Sdk PyPi publishing

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: sdk

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Build sdist and wheel
        run: |
          python -m pip install --upgrade pip
          pip install build
          python -m build --sdist --wheel

      - name: Show dist contents (debug)
        run: ls -la dist || true

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.8.11
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages-dir: dist
          skip-existing: true
